### PR TITLE
fix(current-user): guard against null when checking for user

### LINKED ISSUE #22: TypeError: Cannot read property 'external_id' of null
Sentry Issue: [CAMPAIGN-API-1](https://sentry.io/organizations/debt-collective/issues/1364957041/?referrer=github_integration)

```
TypeError: Cannot read property 'external_id' of null
  File "/usr/src/app/resolvers/index.js", line 21, in currentUser
    if (!context.User.external_id) {
  File "/usr/src/app/lib/sentryWrapper.js", line 8, in null.<anonymous>
    const result = await resolverFn(...args)
  ?, in Generator.next
  ?, in new Promise
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by orlando**
**What:**
guard against null when checking for user

**Why:**
Fix #22 

**How:**

- Make sure we have a user before checking for `external_id`

### CODE REVIEW

File: models/stubs/index.js [hunk 1]
```diff
@@ -8,20 +8,22 @@ module.exports = {
...
-    slug: faker.lorem
-      .words(2)
-      .toLowerCase()
-      .split(' ')
-      .join('-'),
-    ...fixedData
+    slug: faker.random.uuid()
   }),
   createActions: (fixedData, amount = 2) => {
-    return Array(amount).fill({
```
Comment (duranmla) [inline models/stubs/index.js]: Just out of curiosity what was the problem with this approach that you change to the for loop?

File: resolvers/__tests__/UserActions.spec.js [hunk 2]
```diff
@@ -7,7 +7,13 @@ const { Mutation, Query } = require('../UserActions')
 const faker = require('faker')
 const _ = require('lodash')
 
-afterAll(() => Model.knex().destroy())
+afterAll(async () => {
+  await UserAction.query().delete()
```
Comment (duranmla) [inline resolvers/__tests__/UserActions.spec.js]: Why the delete on every model is needed?

File: resolvers/__tests__/index.spec.js [hunk 3]
```diff
@@ -94,28 +94,6 @@ describe.skip('Query resolvers', () => {
     expect(actionsIds).toEqual(targetedCampaignActionsIds)
   })
 
-  it("returns the 'UserActions' for a given user", async () => {
```
Comment (duranmla) [inline resolvers/__tests__/index.spec.js]: We are not longer returning UserActions within a user?

File: resolvers/index.js [hunk 4]
```diff
@@ -19,11 +19,13 @@ const queryResolvers = {
    * Retrive user using Cookies
    */
   currentUser: async (root, args, context) => {
-    if (!context.User.external_id) {
+    const { User: user } = context
+
+    if (!user || !user.external_id) {
```
Comment (duranmla) [inline resolvers/index.js]: **nice to have.** probably we should add `optional-chaining`
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
- https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

File: models/stubs/index.js (hunk 1 above)
Comment (orlando) [reply models/stubs/index.js]: This was causing an error given slug need to be unique. `Array.fill` passes the same values to every element of the Array

File: resolvers/__tests__/UserActions.spec.js (hunk 2 above)
Comment (orlando) [reply resolvers/__tests__/UserActions.spec.js]: I think we need to clean before and after every test, if this test executes at last it will leave records in the test database.

File: resolvers/__tests__/index.spec.js (hunk 3 above)
Comment (orlando) [reply resolvers/__tests__/index.spec.js]: Yeah this endpoint changed, we now ask for a specific actions by slug. These tests were failing due the code being removed.

File: resolvers/index.js (hunk 4 above)
Comment (orlando) [reply resolvers/index.js]: I like this, let me see if I can integrate that into this PR
